apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "urlaubsverwaltung.fullname" . }}
  labels:
    {{- include "urlaubsverwaltung.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "urlaubsverwaltung.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "urlaubsverwaltung.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "urlaubsverwaltung.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- if .Values.customizedManagementServer.enabled }}
            - name: http-management
              containerPort: {{ .Values.customizedManagementServer.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.postgresql.enabled }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ include "urlaubsverwaltung.postgresql.fullname" . }}:{{ .Values.postgresql.primary.service.ports.postgresql }}/{{ .Values.postgresql.auth.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "urlaubsverwaltung.postgresql.fullname" . }}
                  key: password
            {{- end }}
            {{- if .Values.customizedManagementServer.enabled }}
            - name: MANAGEMENT_SERVER_PORT
              value: {{ .Values.customizedManagementServer.port | quote }}
            - name: MANAGEMENT_SERVER_ADDRESS
              value: {{ .Values.customizedManagementServer.address }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.extraEnvFrom }}
              {{- tpl . $ | nindent 12 }}
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
          {{- end }}
